#!/usr/bin/env python2.7

import sys
import os.path
dev_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
sys.path.insert(0, dev_path)

import argparse

import ck.ssl_library

parser = argparse.ArgumentParser(description='Check a certificate against the CA')

parser.add_argument('-n', '--name',
                    default='normal', 
                    help='Name used for the filenames')

parser.add_argument('-o', '--output_path',
                    default='', 
                    help='Output path')

args = parser.parse_args()

if args.output_path != '':
    output_path = args.output_path
else:
    sys.stdout.write("Please confirm input directory []: ")
    output_path = raw_input().strip()

with open(os.path.join(output_path, 'ca.crt.pem')) as f:
    ca_crt_pem = f.read()

with open(os.path.join(output_path, args.name + '.crt.pem')) as f:
    crt_pem = f.read()

is_valid = ck.ssl_library.verify_ca(ca_crt_pem, crt_pem)

print("Is valid? %s" % (is_valid,))

sys.exit(0 if is_valid is True else 1)
